### ISSUE TITLE
Unable to deploy the code

### ISSUE THREAD

**Issue by DebajyotiMCA** [trailheadapps/lwc-recipes-oss#21]
=== Deploy Errors
PROJECT PATH  ERRORS                                 
────────────  ───────────────────────────────────────
N/A           No MODULE named markup://ui:input found

**Comment by muenzpraeger** [comment]
This repo is for LWC off platform (for example Heroku, GCP, AWS).

For the Salesforce platform use https://github.com/trailheadapps/lwc-recipes

**Comment by 001azim** [comment]
> This repo is for LWC off platform (for example Heroku, GCP, AWS).
> 
> For the Salesforce platform use https://github.com/trailheadapps/lwc-recipes

i hosted the lwc node app in my server, http://lwr-app.rangerfusion.com/ when i put the url in browser and inspect it says the lwc component i given as root is not found ,
but when i run locally it works 

it is because the <script type="module" src="/1/module/esm/0/l/en-GB/mi/%40lwrjs%2Fapp-service%2Fnxt%2Fmodule%2Fesm%2Fv%2F0_12_4/latest/@lwrjs_app-service_nxt_module_esm.js"></script>
<link rel="modulepreload" href="/1/module/esm/0/l/en-GB/mi/c%2Fbooklet%2Fv%2F0_0_1/latest/c_booklet.js" />
  is not found in the hosted app how to fix this?

Edit
