### ISSUE TITLE
Proposal: Add New Category for Commonly Used Components

### ISSUE THREAD

**Issue by valon-loshaj** [trailheadapps/lwc-recipes-oss#528]
### Summary

I would like to propose the addition of a new category in the Lightning Web Components recipes app. This new category will contain components that I've found over the years are commonly used across various projects. Including recipes for these components will help developers avoid the need to rewrite these components for each new project.

### Suggested Solution

**Proposed Components**:

**Drawers**: Slide-in panels for additional content.
**Accordions**: Expandable sections to toggle content visibility.
**Tabs**: Organized sections displayed one at a time.
**Modals**: Overlay dialog boxes for additional content.
**Tooltips**: Hover-based information pop-ups.
**Toast Notifications**: Alerts and messages for users.

I'm proposing we call this new category of components 'Common Components' or 'Project Essentials'.

Would love to work on these components as my way of helping contribute!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozil** [comment]
Hi @valon-loshaj, thanks for the suggestion. I agree that it would be useful however, the purpose of the LWC Recipes OSS sample app is to demonstrate LWR core functionalities, not so much to showcase and distribute reusable custom components. If we wanted to go down the path of distributing reusable components, we would need another project with proper packaging (NPM).

Our team is not considering this path at the moment due to bandwidth considerations. To be fully transparent, our efforts are currently focused on Platform and Data Cloud.

**Comment by valon-loshaj** [comment]
Thanks for the reply @pozil !

If there are any Salesforce OSS projects that can use support from contributors let me know. Salesforce has had a tremendously positive impact on my career and development so would love to give back by contributing to the community.
