### ISSUE TITLE
Example with async api call

### ISSUE THREAD

**Issue by ejangi** [trailheadapps/lwc-recipes-oss#64]
Hi Team,

I'm currently trying to figure out how to @wire a component property to a Google Firestore call. Obviously, this is an async call. So, based on the example here (which is essentially a synchronous call to the static contacts JSON) I'm not sure how to make this work.

Are you able to add an example with that includes something like this so I can follow along?

Thanks,
James.

**Comment by pozil** [comment]
Hi James,

You can do that in several way.The simplest way is just to use the fetch API like this:

**Comment by pozil** [comment]
Hi James,

You have two options for implementing async API calls.

The simplest is to directly use the Fetch API in you component like this:
https://github.com/trailheadapps/lwc-recipes-oss/blob/master/src/modules/recipe/miscRestApiCall/miscRestApiCall.js

Otherwise, you can create a custom wire adapter like this:
https://github.com/trailheadapps/lwc-recipes-oss/blob/master/src/modules/data/wireGetContactListProvider/wireGetContactListProvider.js

As you've noticed we're just returning data from a JSON file in this example. However, you can change that and call the Fetch API then, fire the `ValueChangedEvent` when the Fetch promise resolves.

Here's a more advanced example of a custom wire adapter taken for the LWC repository:
https://github.com/salesforce/lwc/tree/master/packages/%40lwc/wire-service#example-wire-adapter-implementation

**Comment by muenzpraeger** [comment]
One word of warning: there will be a reform of the `wire` adapter (see the RfC [here](https://github.com/salesforce/lwc-rfcs/blob/master/text/0000-wire-reform.md)) at some point not too far out.

**Comment by ejangi** [comment]
Thanks @pozil and @muenzpraeger, that last example is the one I'm currently following, but the connect event doesn't seem to fire in my case. I ended up posting the full attempt on [stackoverflow](https://salesforce.stackexchange.com/questions/288852/how-to-wire-an-external-rest-api-call-with-lwc-oss). You can take a look at [my source](https://github.com/ejangi/lwc-test/blob/master/src/modules/my/greeting/greeting.js) if it's any help.

**Comment by muenzpraeger** [comment]
@pmdartus ^^
